// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2zp2pVGQtCRsLvgqRMsj6vIZxh-2wSnM',
    appId: '1:597140137923:web:bc848926c7a40e75337f76',
    messagingSenderId: '597140137923',
    projectId: 'digital-business-card-83a4a',
    authDomain: 'digital-business-card-83a4a.firebaseapp.com',
    databaseURL: 'https://digital-business-card-83a4a-default-rtdb.firebaseio.com',
    storageBucket: 'digital-business-card-83a4a.appspot.com',
    measurementId: 'G-L0CSEE6EF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGvWpgFjh4TzvqfFVdjYJUi0q_5m_Bo6U',
    appId: '1:597140137923:android:f8bcbef56eddb178337f76',
    messagingSenderId: '597140137923',
    projectId: 'digital-business-card-83a4a',
    databaseURL: 'https://digital-business-card-83a4a-default-rtdb.firebaseio.com',
    storageBucket: 'digital-business-card-83a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNARJjSHex5PHPvnqaSWFkXV1bz1UR_Dg',
    appId: '1:597140137923:ios:97565a1fc0914020337f76',
    messagingSenderId: '597140137923',
    projectId: 'digital-business-card-83a4a',
    databaseURL: 'https://digital-business-card-83a4a-default-rtdb.firebaseio.com',
    storageBucket: 'digital-business-card-83a4a.appspot.com',
    iosClientId: '597140137923-0r5kakqb99tkdjt3p0o3imjd1qq0vbdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalBusinessCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNARJjSHex5PHPvnqaSWFkXV1bz1UR_Dg',
    appId: '1:597140137923:ios:97565a1fc0914020337f76',
    messagingSenderId: '597140137923',
    projectId: 'digital-business-card-83a4a',
    databaseURL: 'https://digital-business-card-83a4a-default-rtdb.firebaseio.com',
    storageBucket: 'digital-business-card-83a4a.appspot.com',
    iosClientId: '597140137923-0r5kakqb99tkdjt3p0o3imjd1qq0vbdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalBusinessCard',
  );
}
